db:
  image: postgres
redis:
  image: dockerfile/redis
web:
  build: .
  command: ./run.sh
  volumes:
    - .:/code
    #- ../django-custom-field/custom_field:/usr/local/lib/python2.7/dist-packages/custom_field
    #- ../django-report-builder/report_builder:/usr/local/lib/python2.7/dist-packages/report_builder
    #- ../django-report-utils/report_utils:/usr/local/lib/python2.7/dist-packages/report_utils
    #- ../django-constance/constance:/usr/local/lib/python2.7/dist-packages/constance
  ports:
    - "8000:8000"
    - "5555:5555"
  links:
    - db
    - redis
